### ISSUE TITLE
Many HTML forms not loading - page unavailable

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#173] opened 2016-05-09 10:28 UTC
Reported by @NikosLiosis and replicated by me. 1Mng/All lgs and 1lg/All Mng html forms come up as "page unavailable". 1mng/ All cog sets as well as reference html forms are behaving normally.
Clearly this takes priority over all other issues until resolved.

**Comment by runjak** [comment] 2016-05-09 10:45
Yes, I agree. I'll have a look at this immediately.

**Comment by runjak** [comment] 2016-05-09 10:47
Ok, the good news is this:
I can reproduce this problem locally and should have it fixed soon.
I'll deploy the fix once I've got it.

**Comment by runjak** [comment] 2016-05-09 10:55
Alright, I have a fix for this and will deploy it next.

In hindsight this problem would have been easy to avoid with some simple tests
that just check if every view of our site is reachable without errors.
Django already has something for this, but I could use a bit of time to figure out how to use it.
The specific problem arose because I migrated JSON fields in the CoganteClass table to become actual columns, but didn't catch all code that still expected JSON fields to exist.

**Closed** 2016-05-09 10:55 UTC
Labels: 0th, Website: Bug

**Comment by runjak** [comment] 2016-05-09 11:12
Deployment on the server is finished now. You should be able to verify that the mentioned views are working again.
