### ISSUE TITLE
Bug in root reference form and language fields?

### ISSUE THREAD

**Issue by leszekjocz** [lingdb/CoBL#382] opened 2016-12-20 16:57 UTC
Does it look like that on my machine only?
![1](https://cloud.githubusercontent.com/assets/16056017/21359809/b3d0f594-c6dd-11e6-8de6-2a0b9013f17d.png)
![2](https://cloud.githubusercontent.com/assets/16056017/21359808/b3cf2b2e-c6dd-11e6-80e6-258098136fbc.png)

**Comment by runjak** [comment] 2016-12-21 10:27
Screenshots from my development version of CoBL:
![screenshot_2016-12-21_11-24-48](https://cloud.githubusercontent.com/assets/5417642/21385796/4968ebf6-c770-11e6-9e08-c12ee887d125.png)
![screenshot_2016-12-21_11-24-55](https://cloud.githubusercontent.com/assets/5417642/21385795/49689a0c-c770-11e6-97a4-3b3b077ea5f1.png)
Screenshots from viewing the same pages on the server:
![screenshot_2016-12-21_11-26-31](https://cloud.githubusercontent.com/assets/5417642/21385816/639e383c-c770-11e6-830b-3d8757c49020.png)
![screenshot_2016-12-21_11-26-38](https://cloud.githubusercontent.com/assets/5417642/21385817/639ef344-c770-11e6-8c78-c25f48ae5428.png)
Viewed URLs are:
* http://cobl.info/meaning/bad/cognateclasslist/
* http://cobl.info/language/OldPolish/wordlist/Jena200/

**Comment by runjak** [comment] 2016-12-21 14:45
@leszekjocz I'm not sure what the possible bug here is or could be. As far as I understand it's intended that `Root ref. form` and `Root ref. language` only be editable from `1 meaning all cognate sets` view.

**Comment by leszekjocz** [comment] 2016-12-21 21:06
It's not the point that they are uneditable.
The point is that there is one single root reference form displayed for all lexemes (probably 'random', now I have a different one than before) . E.g. on my machine ALL Old Polish lexemes have *u̯ei̯d- as the root reference form, which is a nonsence.

**Comment by leszekjocz** [comment] 2016-12-21 21:07
On another computer all Old Polish lexemes have 'saxt' as root reference form and 'Kumzari' as root reference language.

**Comment by PaulHeggarty** [comment] 2016-12-21 21:21
This really does seem to be a critical bug.  I’ve therefore put it to priority level 0.  We should probably revert whatever parts of the code are causing this back to a previous stage, because this clearly is making the site entirely unusable, for some users at least.

**Comment by PaulHeggarty** [comment] 2016-12-21 21:26
I can confirm that I get the same problem with Old Polish, and Old Novgorod too, and French, and Ancient Greek.  It's thw whol `1-Language, All Meanings` form that is broken here.  
(The `1-Meaning, All Languages` form seems ok, from a brief look.)

**Comment by leszekjocz** [comment] 2016-12-21 21:37
There is a similar problem in the 1-meaning, All Cognate Sets view.
Once there is no root reference form and language entered, a random root reference form and language is displayed.

**Comment by RolandPooth** [comment] 2016-12-22 09:13
I also had this bug before two day and thought it would be a contemporary server problem, but I can confirm this bug for today (22 December) with all Indic masks.
Random root reference forms also occur in the 1 meaning all cognate sets in grey.
![bildschirmfoto 2016-12-22 um 10 11 16](https://cloud.githubusercontent.com/assets/16067862/21420668/32f4fc56-c82f-11e6-92f4-7c898ead2fd5.png)

**Comment by runjak** [comment] 2017-01-05 13:22
I think this problem may have been introduced by commit fc04481ec8bffedefeddfc02b77d85ce395e2d2c in relation to #364.

Currently the placeholders for the `Root ref. form` field are calculated like [this](https://github.com/lingdb/CoBL/blob/9f185194972b70783c99321cf6ac4535627f6191/ielex/lexicon/models.py#L1256-L1303):
1. If the `CognateClass` entry has a `root_form` given we display that.
2. If the `CognateClass` has exactly one lexeme in it, we use the `romanised` entry of that lexeme.
3. If the `CognateClass` is marked as `loanword` and a `sourceFormInLoanLanguage` is given, we use the `sourceFormInLoanLanguage` inside `()`.
4. We search for the most specific clade to the set of languages that belong to the current `CognateClass`. In this set of languages that belong to the same `CognateClass` and clade, we search for:
    1. A language that is marked as `representative`. If such a language is found we use the `phoneMic` entry of the lexeme that belongs to this language and the `CognateClass` if the `phoneMic` entry is not empty.
    2. We do the same search again but for languages that are marked as `exampleLanguage`.
    3. We do the same search again but use all languages that fit into the current `CognateClass` and `Clade` regardless of `exampleLanguage` or `representative` state.
5. We don't know what else to do and return `''` as the current `Root ref. form` content.

My hunch would be that we end up with case `4.iii` when we don't want it to happen.
That is the `Root ref. form` ends up being the `phoneMic` field of an arbitrary language that belongs to the same `CognateClass` but it would be more helpful not do display anything.

**Comment by leszekjocz** [comment] 2017-01-05 13:43
I'm not sure if I understand you correctly but it seems to me that you still don't catch the problem.
The fail happens already at "1". All lexemes in the languages I and Paul mentioned do have an appropriate root reference form entered. However, instead of this entry a completely random rubbish is displayed.

**Comment by PaulHeggarty** [comment] 2017-01-05 23:12
Well, it isn’t really random rubbish -- not zX3^*!"a>> or something.  It's just a root form that doesn’t correspond to that cognate set, but to a different cognate set.

**Comment by runjak** [comment] 2017-01-06 08:09
Hm. I think the last two comments helped to point me in the right direction.
The problem appears to be that to reduce load on the database I implemented an optimization that does more harm than good:
The placeholders are only to be computed once for each entry when it is loaded and not several times. It appears that this computation is not done only once for every entry, but once for all entries being loaded. This results in the wrong data being shown multiple times.

**Comment by runjak** [comment] 2017-01-06 08:39
I've deployed an update that should fix the problem.
Please check if the issue still persists.

**Comment by m-scarborough** [comment] 2017-01-06 08:57
The issue on both the 1-language view and the 1-meaning view look fixed to me on my machine.  Thanks Jakob.

**Comment by runjak** [comment] 2017-01-06 10:36
Cool, thanks for verifying @m-scarborough

**Closed by runjak** 2017-01-06 10:36 UTC
Labels: 0th, Website: Bug
