### ISSUE TITLE
My changes are not being saved?

### ISSUE THREAD

**Issue by tonyakdewey** [lingdb/CoBL#111] opened 2016-03-11 04:08 UTC
I've input the same data three times now, but it doesn't show up when the page reloads.

-----

Todo added by @runjak:

- [x] Add `AbstractTimestamped` class. This will be the general concept that allows to track for each entry of a table when it was changed last by whom.
- [x] Add `AbstractTimestamped` to `authors` table.
- [x] Add `AbstractTimestamped` to `cognate classes` table.
- [x] Add `AbstractTimestamped` to `cognate judgement` table.
- [x] Add `AbstractTimestamped` to `clades` table.
- [x] Add `AbstractTimestamped` to `language` table.
- [x] Add `AbstractTimestamped` to `sndComp` table.
- [x] Add `AbstractTimestamped` to `lexeme` table.
- [x] Add `AbstractTimestamped` to `meaning` table.
- [x] Remove unnecessary `modified` fields.

**Comment by runjak** [comment] 2016-03-11 09:04
That's not good and I imagine frustrating as well.
Can you hint me to which input form or URL you're working at?

**Comment by runjak** [comment] 2016-03-11 13:27
Is this possibly the same as #101?

**Comment by tonyakdewey** [comment] 2016-03-11 17:22
It possibly is (not being a programmer, I have no idea).

I was working on Old Swedish (http://134.76.24.144/language/Old_Swedish/).  Changes that I made two days ago (through HOW) show up just fine, but changes that I made yesterday (from HUNT onwards) are not showing up.

**Comment by runjak** [comment] 2016-03-12 10:21
OK, thanks for specifying!
The URL will make it easier for me to reproduce the problem.
From what I found when I investigated #101 more I think the issues are indeed related and I need to fix them soon. With a bit of luck this will be resolved till Monday.

**Comment by runjak** [comment] 2016-03-12 13:02
I've just deployed aa0b4bf0fe67343fc17eaf94eb6e5c8a65b884cb on the server and this should make it possible to enter data again. Please reopen this issue if the problem persists.

**Comment by CasFre** [comment] 2016-05-02 13:09
Hi, I guess I just had the same problem as @tonyakdewey.
Yesterday I tried to enter some data that were still missing in the PIE (simple things like root language = PIE) list but the changes were not being saved.
Now I had the same thing on http://cobl.info/meaning/yesterday/languagelist/01_Reference/ when trying to add a root form and root language for the Classical_Armenian lexeme "erēk".

**Comment by CasFre** [comment] 2016-05-02 13:12
Its the same with the Old Church Slavonic lexeme for [yesterday].

**Comment by runjak** [comment] 2016-05-02 18:20
OK, this sounds like potentially bad news.
I'll have a look at this after deploying my recent work on #153 this evening.

**Comment by PaulHeggarty** [comment] 2016-05-02 20:36
I wonder if this is a wider problem with the server or backup system reverting to earlier stages of the database.  We have had this before, repeatedly, and it was never fixed other than by hunting for the deleted data and reapplying them.  Note that Sound Comparisons has lost data for phonetic transcriptions of many Celtic languages (the house word, and numbers 1 to 10).  And we lost a lot of the links to online dictionaries a few weeks back, too.

**Comment by CasFre** [comment] 2016-05-02 20:50
Okay, maybe my problem is a bit different from @tonyakdewey's and that which @PaulHeggarty describes: One could say that my changes were not being _accepted_: I entered some data, pressed the "save"-button, the page reloaded, but afterwards the same blank fields re-appeared as before my entries.

**Comment by tonyakdewey** [comment] 2016-05-02 22:42
@CasFre, that's exactly what was happening to me last month or whenever it was.  It's not happening anymore (the changes that I made yesterday show up today).

**Comment by runjak** [comment] 2016-05-03 12:46
To mitigate this problem I've had a discussion with @Bibiko today about how to better ensure consistency of entered data.
The resulting idea is to add fields `last touched :: timestamp` and `last editor :: Author` to each entry, and to use these entries for two tasks:

* To identify collisions resulting from concurrent edits and resolve the resulting conflict.
* To proactively notify users about ongoing changes in the database.

**Comment by runjak** [comment] 2016-05-03 15:40
Note to myself:
The `last touched` and `last editor` fields could potentially be easily added via an [abstract model](http://charlesleifer.com/blog/django-patterns-model-inheritance/) that would allow me to have this functionality ready as a mixin so that I could inject it into several existing models and *simply* expand their functionality in a standard fashion.
The models currently have more or less standardized versions of `setDelta` and `is_unchanged`/`isChanged` methods, that could be replaced with more generic variants.
This approach would also likely reduce the lines of code and thereby reduce the potential for errors from my side.

**Comment by runjak** [comment] 2016-05-06 09:59
Several tables already have `modified` fields that appear to be rarely used.
When continuing the implementation of `AbstractTimestamped` it would make sense to remove these. I'll edit the topmost comment in this issue to have a tasklist for this issue there.

**Comment by CasFre** [comment] 2016-05-11 09:37
Another problematic case:
The two fields for root language of the two lexemes for [here] in Ancient Greek are again linked somehow so that characters entered in one of them automatically also appear in the other one. Moreover, the entered data aren't being saved:
![problem eintrage_ancient greek](https://cloud.githubusercontent.com/assets/17431124/15176730/cd3f7df0-176c-11e6-8a56-57a0b7f2aa3a.jpg)

**Comment by runjak** [comment] 2016-05-11 10:40
Note to myself:
The lexemes table will be a bit of a tricky bit here.
Since there are also fields from (a single) cognate class belonging to a lexeme,
these fields will need separate timestamps attached so that I can track them correctly.
Without this addition I would either fail to track lexemes or cognate classes without error.

**Comment by runjak** [comment] 2016-05-11 10:43
@CasFre the mentioned fields being linked is a necessary evil because the `Root Language` is a property of the cognate class that both lexeme entries belong to and not of the individual lexemes. The fields not being saved is however a real problem.

**Comment by runjak** [comment] 2016-05-12 12:17
Alright. I think I have the basic functionality for the `lastTouched` and `lastEditor` fields done now. The latest changes to this will be deployed with the next update.
There are two remaining things I'd like to do with this issue:

1. A bit of cleanup is left for some tables which now have a `modified` and a `lastTouched` column both having the same behaviour. For consistency and to remove unnecessary redundancy it would be best to remove the `modified` column from these tables.
2. If a collision occurs where two users edit data independently of each other, one of them currently gets a text message that tries to inform them that some data didn't go trough.
It looks like this: 
![screenshot_2016-05-12_14-12-34](https://cloud.githubusercontent.com/assets/5417642/15214186/e77b1d98-184b-11e6-9907-139d9a3b677b.png)
This situation could be improved by providing a form that displays the differences between the record sent by a user and the one already in the database so that problems like these could be resolved easier.

**Comment by runjak** [comment] 2016-05-31 09:31
Functionality to support resolving edit errors will be deferred for now.
A bit of cleanup will be done on the `modified` fields and afterwards this issue will be closed again.

**Closed** 2016-06-02 13:25 UTC
Labels: 0th, 1st, Website: Bug
