### ISSUE TITLE
Fix the "Select language list" and "Select meaning list"-dropdown menus.

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#158] opened 2016-04-27 09:19 UTC
Maybe you're just about abolishing those lists for the sake of more buttons ;-) , but:
On a 1 mean - all languages page I tried to change the language list via the dropdown menue but while reloading the page it always jumps back to the standard 2016-04-18_129 list.
I also tried the "select meaning list"-menu on a 1 lang - all mean pages and it shows the same problem, resetting to the Jena200-list.

**Comment by cormacanderson** [comment] 2016-04-27 11:10
This problem is extremely frustrating and I am upping its priority. There is a workaround, which is to select a language, then click on the CoBL icon in the top left, which brings you back to the homepage, then to change the meaning list, then to click 1lg/all mngs. Similarly with the language list, you can change it on the homepage, but not e.g. on the language references page.

**Comment by CasFre** [comment] 2016-04-27 11:18
Thanks for the hint at that interim solution!

**Comment by runjak** [comment] 2016-05-03 08:25
This issue appears to have solved itself, is that correct?
If this is still a problem please reopen the issue.

**Comment by runjak** [comment] 2016-05-03 12:34
This issue still persists as seen in a meeting just now.

**Comment by cormacanderson** [comment] 2016-05-11 07:56
As far as I can see, the behaviour of the language lists and meanings lists is a little different. The meanings list very quickly reverts to the Jena 200 if you move between pages, even just selecting a language - the workaround above is the only way I have been able to access other meaning lists. The language lists, on the other hand, seem to be a bit more sticky.

**Comment by runjak** [comment] 2016-05-18 08:46
I've deployed a fix for this and it appears to be working now on [CoBL](http://cobl.info) with Firefox. Please reopen if the issue still persists somehow.

**Comment by cormacanderson** [comment] 2016-05-19 13:55
The problem persists. On the languages references html form it is possible to change the lists, but not from the page of an individual language. If one clicks on a language from the languages references html form, then there is reversion to the default (Jena 200) list and it is impossible to change.

**Comment by runjak** [comment] 2016-05-20 07:33
Alright. Thanks for notifying!

**Comment by runjak** [comment] 2016-05-25 13:32
By `the page of an individual language` I assume that you refer to the the view of all meanings of the current meaninglist against a single language that is accessible at [/language/](http://www.cobl.info/language/). The next/previous links for languages at the top of the page should use next/previous languages from the currently selected languagelist.
![screenshot_2016-05-25_15-24-32](https://cloud.githubusercontent.com/assets/5417642/15541607/8ce6bb8e-228d-11e6-8c33-038ae954b730.png)
![screenshot_2016-05-25_15-24-50](https://cloud.githubusercontent.com/assets/5417642/15541606/8cd843c4-228d-11e6-8db5-8e39068d134c.png)
![screenshot_2016-05-25_15-26-03](https://cloud.githubusercontent.com/assets/5417642/15541605/8cd79bc2-228d-11e6-8a6e-9ae136453927.png)
Using the selection lists in the top menu when viewing this page works for me in both firefox and chromium with [cobl.info](http://cobl.info).
Could you try logging out and in again if my assumptions about the visited page are correct to see if this changes something? If my assumptions are false it would be good if you could give me the URLs that you're looking at when you try to change one of the lists and the URL you end up viewing afterwards.

**Comment by cormacanderson** [comment] 2016-05-26 11:29
Yes, what you are talking about works for me as well, which is good. However, that's not really the most common way that I navigate between languages. The problem is that if I am on the languages references html form , with the `all` meaning list selected and click on a language to see all the lexemes associated to that language, the meaning list reverts to the Jena200. This is still happening.

**Comment by runjak** [comment] 2016-05-26 11:44
Ah! I misunderstood. Sorry.

**Comment by runjak** [comment] 2016-05-26 12:00
The problem here is in [ielex/urls.py](https://github.com/lingdb/CoBL/blob/d9c538257b1ffafdaba46353aeec653097daba25/ielex/urls.py#L66) where the used route for links from the language report to the language*meanings table always resets the wordlist to `Jena200`.
To circumvent this I'm now specifying the correct links directly.

**Comment by runjak** [comment] 2016-05-26 13:05
I've fixed the problematic links and deployed the changes.
@cormacanderson would you like to have a look in case I missed something again?

**Closed** 2016-05-30 14:29 UTC
Labels: 0th, Website: Bug
