### ISSUE TITLE
Enable languages to be cloned

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#41] opened 2016-01-17 12:26 UTC
This involves cloning all of the entries for a given language, so that we can start work on a new language on the basis of an existing one, which will often be useful when we want to add in dialect variants etc.

Since this includes #43, tasks for this issue are:

- [x] Enable languages with their corresponding lexemes to be cloned.
- [x] Add a blank language that has empty lexeme entries for all meanings.

Issues discovered when discussing this with @cormacanderson :

- [x] Move clone button to language reference table.
- [x] Specify that the wanted language name for cloning is the URL name.

**Comment by cormacanderson** [comment] 2016-01-17 12:29
Problem identified by @leszekjocz here https://github.com/lingdb/ielex2/issues/7

**Comment by cormacanderson** [comment] 2016-01-17 12:30
https://github.com/lingdb/ielex2/issues/35 must also be considered when this is being implemented

**Comment by runjak** [comment] 2016-05-09 12:02
When creating a new language list, an existing language list to base the new one upon will already be selected. Thus the functionality to clone language lists is already existing, and this issue is about creating the blank language list.
I've written code to add a blank language list, which also makes sure that it's not possible to add languages to that specific list.

**Comment by cormacanderson** [comment] 2016-05-09 12:07
What is meant here is not the ability to clone a language list, but rather the ability to clone a language, with all its entries. So, for example, if we want to add Saxon German, we can clone the German list, with all its entries, and then amend it, rather than starting from scratch. Reopening this and amending the description to be clearer.

**Comment by runjak** [comment] 2016-05-09 12:10
Ah, thanks. I see my mistake. I assume then that we don't need an empty language list, but rather an empty lexeme list.

**Comment by cormacanderson** [comment] 2016-05-09 12:11
Yes, exactly, sorry for the lack of clarity.

**Comment by runjak** [comment] 2016-05-09 12:12
Well - the upside is that using git it's not that hard to roll back my work to an earlier state where we don't have the language list we don't need .)

**Comment by runjak** [comment] 2016-05-18 11:07
I have an input dialog reachable from the language lexeme table:
![screenshot_2016-05-18_13-02-46](https://cloud.githubusercontent.com/assets/5417642/15356419/e24b3f4a-1cf8-11e6-8b71-dc8b096491f8.png)
This dialog would allow the creation of a new language that has the following properties:
* The language has a lexeme entry for every meaning in the current meaninglist
* The language is added to the current language list
* If emptyLexemes is checked, all lexeme entries will be empty.
* If emptyLexemes is left unchecked, all lexeme entries will copy their data from the currently viewed table.

A few things remain open:
* Is this somehow the functionality that we want?
* The process of cloning a language is not really fast, so I'd like to improve this.

**Comment by runjak** [comment] 2016-05-18 11:13
Current statistics for cloning a language:
![screenshot_2016-05-18_13-12-54](https://cloud.githubusercontent.com/assets/5417642/15356645/44d15428-1cfa-11e6-942f-e0dede0d687a.png)

**Comment by runjak** [comment] 2016-05-18 11:42
I think more recent timings look better:
![screenshot_2016-05-18_13-41-39](https://cloud.githubusercontent.com/assets/5417642/15357317/4afa3488-1cfe-11e6-87df-61c5a2e588f3.png)

**Comment by runjak** [comment] 2016-05-18 11:49
I believe cb930b8 solves this issue.
Once it is deployed I'll comment here so that you can see if it does what you expect it to do.

**Comment by runjak** [comment] 2016-05-18 13:22
When viewing all lexemes for a single language you now have a button showing two documents (duplication). You can use this button to clone a language.
![screenshot_2016-05-18_15-19-07](https://cloud.githubusercontent.com/assets/5417642/15359975/024e4fb8-1d0c-11e6-8469-a15acad4b1de.png)
When clicking it a dialog will open asking you to specify a name for the new language and whether you want lexemes for it to be empty.
I'd welcome feedback concerning this functionality because I feel a bit uncertain about the feature fitting your needs. If all is fine I guess we can close this issue.

**Comment by cormacanderson** [comment] 2016-05-19 14:29
Thanks for this Jakob. I started testing it, but it shows an error message for me every time "Sorry, a problem occurred when cloning the language". I tried with a number of languages, including Latin, which certainly meets the criteria you outline (although they could be relaxed). For that reason I am reopening. Speed is not so much of a consideration here, as this is not something that we will be using every day, although it is extremely useful in terms of speeding things up.

**Comment by runjak** [comment] 2016-05-20 07:34
Thanks for the feedback - I'll look into this to see what could cause the problem.

**Comment by runjak** [comment] 2016-05-25 13:07
It would likely be best to have a look at this together on the CoBL server instance.
Because I cannot reproduce this problem locally and would hesitate changing something like this on the server on my own.

**Comment by runjak** [comment] 2016-05-25 13:08
I think that this may be a timing issue where the page takes so long that the request gets aborted somehow. But tying this out and reading the server logs at the same time should yield more information.

**Comment by PaulHeggarty** [comment] 2016-05-26 13:22
Was this a deliberate decision to have the clone button on the 1 language all meanings table, rather than on the reference languages table, where I would have thought it would be more natural to put it?

**Comment by runjak** [comment] 2016-05-26 13:51
This was just the first place that came to mind for me because of the cloning being concerned with the lexemes in a given language/meaningList combination which is the same thing that view is concerned with already.
If you prefer it we can have this button in the language reference list instead.
In that case I would need some additional code to specify the language that should be cloned.

**Comment by PaulHeggarty** [comment] 2016-07-19 13:33
Probably because we’ve moved to 'Current' as the default language list, we now have a problem editing language lists. I’ve just cloned a new language, `LateVedic`, and want it to go into the Current list. But when I try to edit that list, it only shows languages already in the Current list. The newly cloned language only went into the `all` list, but if I edit the `Current` list, I can’t see it to add it.  So … in the edit language list form, it always needs to display also the languages in the all list, so that they can be added to another list. 
Ideally, when cloning a language, the user should also be asked which list he wants to add it to (as well as 'all', which should be automatic), with that set to 1Current` by default.
Unfortunately this too is urgent, because somebody is waiting to enter the data for this new language ugently.  If the fix will take too long, then for now could you just manually add `LateVedic` to the `Current` list, and worry about editing the code for cloning later.

**Comment by runjak** [comment] 2016-07-20 13:41
I'll add `LateVedic` to the `Current` list directly.
Currently when cloning a Language it should be added to the currently viewed language list as per the code in [views.py](https://github.com/lingdb/CoBL/blob/90ece7e98858671817afafb6ccbe11486fd01404/ielex/views.py#L321-L323):
![screenshot_2016-07-20_15-29-54](https://cloud.githubusercontent.com/assets/5417642/16987929/d4dddee0-4e8e-11e6-8b72-5db7d4cfe71e.png)

I see that the edit form for language lists is currently broken (The list of Excluded languages is empty):
![screenshot_2016-07-20_15-32-21](https://cloud.githubusercontent.com/assets/5417642/16988334/69116586-4e90-11e6-9ed8-ddc616aadba3.png)
I'll see to fix this as well.

**Comment by runjak** [comment] 2016-08-02 11:00
Reopening to implement the following:
When cloning a language without the `blank` option we need the newly created/cloned lexemes for the new language to retain their cognate class judgements.

**Comment by runjak** [comment] 2016-08-02 12:21
Cloning a language should also clone the clade levels and as much of the languages basic data as possible.

**Comment by runjak** [comment] 2016-08-02 12:44
There appear to be problems with the CognateJudgementCitations and the LexemeCitations not being cloned (correctly). This will need to be fixed as well.

**Comment by runjak** [comment] 2016-08-02 13:27
I've developed a fix to copy the citations correctly when cloning a language.
Next step will be to make sure that we also copy the current language meta data like clade levels, iso/glotto codes correctly.

**Closed** 2016-08-02 13:46 UTC
Labels: 0th, Time 2: Hour or Two, Website: Bug
