### ISSUE TITLE
Username not working?

### ISSUE THREAD

**Issue by tonyakdewey** [lingdb/CoBL#377] opened 2016-12-12 16:48 UTC
I can't log in -- get an error message that my username and password do not match.  I haven't changed my password...

**Comment by runjak** [comment] 2016-12-12 19:46
Investigating…

**Comment by runjak** [comment] 2016-12-12 19:49
This appears to have been one of the rare but happening cases where a user slips to being marked as `is_active=false`.

We've had cases like this in the past, but couldn't figure out what the problem is so far.
Since we recently had problems with the server this may be related.

Anyway your login should work again - please check if it does.

**Comment by runjak** [comment] 2016-12-12 20:29
Closing - please reopen if the problem still persists.

**Closed by runjak** 2016-12-12 20:29 UTC
Labels: 0th, Website: Bug

**Comment by tonyakdewey** [comment] 2016-12-12 23:10
Thank you!  It's working now!
