### ISSUE TITLE
Problem in adding lexemes

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#205] opened 2016-06-30 21:18 UTC
An error message appears when I try to add a lexeme (using the plus button at the top of the `1mng all lgs` html form)

**Comment by runjak** [comment] 2016-07-01 07:18
Is this a different issue from the one discussed per mail?

**Comment by runjak** [comment] 2016-07-01 07:33
I'm working on it - should be fixed soon.

**Comment by runjak** [comment] 2016-07-01 07:39
I found a portion of code throwing errors for this specific case.

**Comment by runjak** [comment] 2016-07-01 07:45
I've developed a fix for this that will be deployed soon.
I've also added additional error messages to be displayed to the user in case of future problems so that it should be easier to get some information about future problems in this portion of code.

**Comment by runjak** [comment] 2016-07-01 07:53
I've deployed the patch for this.
If you can verify that this works now we can close this issue.

**Comment by runjak** [comment] 2016-07-01 08:05
Nope - I fixed a different issue, I think - sorry…

**Comment by runjak** [comment] 2016-07-01 08:28
The problem with adding new lexemes appears in both tables:
* 1 meaning all languages
* 1 language all meanings

It appears to be triggered by [ielex/views.py:1791](https://github.com/lingdb/CoBL/blob/047c7bbcedcbfa00ae425b349f65335ed697a30c/ielex/views.py#L1791) where creating a new lexeme fails because of database constraints.

This is code I haven't touched directly yet,
but which likely broke because of changes I made to the underlying database models.

**Comment by nitsnatsnok** [comment] 2016-07-01 09:39
This also affects adding cogante classes by splitting as well as linking to new cognate class on the lexeme page.

**Comment by nitsnatsnok** [comment] 2016-07-01 10:15
#207

**Comment by runjak** [comment] 2016-07-01 11:14
I've deployed an update on the server.
The described problems *should* now be solved, but it's possible that I missed something.
Therefore it would be nice if someone could verify this.

**Comment by cormacanderson** [comment] 2016-11-11 10:28
I have been receiving reports that this problem has resurfaced. Examples are http://cobl.info/lexeme/52338/ and http://cobl.info/lexeme/52339/, which the language author said he created, but which do not appear in the list.

**Comment by runjak** [comment] 2016-11-14 10:17
I can reproduce problems accessing the pages you've linked to.

**Comment by runjak** [comment] 2016-11-14 10:28
Thanks for giving links to the specific lexemes - this made it much easier to find some problem here.
I could already figure out why the page for a single lexeme wouldn't render, but there appears to be a bigger problem underneath.
Somehow we've ended up with lexemes that don't have a meaning.
![screenshot_2016-11-14_11-25-43](https://cloud.githubusercontent.com/assets/5417642/20261246/4a301a4e-aa5d-11e6-988f-ea270d923047.png)
Such lexemes belong to different languages:
![screenshot_2016-11-14_11-25-34](https://cloud.githubusercontent.com/assets/5417642/20261241/440d526c-aa5d-11e6-8abc-82c4a070b522.png)

I'm not sure why it's allowed to have lexemes without a meaning in the database in the first place, but I'll see where this comes from.

**Comment by cormacanderson** [comment] 2016-11-14 11:23
I don't actually remember this happening to me recently but it has in the past. It always seemed quite random. Do you have any more info about the lexeme I tried to add that didn't work?

**Comment by runjak** [comment] 2016-11-14 11:47
The URL would be http://cobl.info//lexeme/52353/
but I haven't deployed the fix for the error you'll see there yet, so here's a screenshot:
![screenshot_2016-11-14_12-43-33](https://cloud.githubusercontent.com/assets/5417642/20263646/f8ed95ac-aa67-11e6-9b82-2a6c7a886ddd.png)

Actually I don't know whether you've added it yourself.
All I can see is that the database thinks that you've been the last one to touch it:
![screenshot_2016-11-14_12-46-19](https://cloud.githubusercontent.com/assets/5417642/20263789/82da2c4e-aa68-11e6-8789-facd0d988886.png)

**Comment by cormacanderson** [comment] 2016-11-14 11:49
Yes, it was the Wakhi expert who brought this problem to my attention, and I tried to enter the lexemes myself. I didn't even realise that one had not gone through, but I tried to create it in the normal way. Sometimes it works, sometimes it doesn't.

**Comment by runjak** [comment] 2016-11-14 12:15
OK - so my suggestion would be this:

1. I'll make sure we can visit the single lexeme pages again to investigate the data there.
2. I can provide a list of lexemes that don't have a meaning attached. I can also group entries based on who touched them last or on which language they belong to. I imagine that this would be helpful to clean the current data.
3. I'll watch out for the initial problem that allows such data to be created in the first place.

**Comment by runjak** [comment] 2016-11-14 19:27
I've removed the following lexemes:
```
47756, 47759, 47761, 47770, 47957, 47958, 47964, 50921, 50922, 49860, 49861, 49888, 49387, 50999, 51229, 51001, 47774, 49344, 49347, 49348, 51009, 50983, 49353, 51243, 51244, 51246, 49464, 49508, 49531, 49246, 47860, 49475, 49541, 49519, 49480, 47909, 49261, 50954, 50929, 52327, 50931, 47878, 51027, 47711, 52340, 47431, 52341, 47432, 52342, 47885, 52343, 52344, 52345, 52346, 50944, 52347, 51021, 47426, 52349, 52350, 47893, 52351, 47894, 49492, 47895, 52363, 52364, 52365, 52366, 52369, 52370, 49240, 49241, 49446, 49235, 49242, 49236, 49447, 49495, 42929, 49496, 49497, 49815, 49430, 49498, 47368, 49499, 49500, 49817, 49558, 49559, 47754, 47764, 49439, 49561, 47376, 49821, 49822, 47378, 49823, 49566, 49825, 47381, 49827, 52300, 49828, 49829, 52301, 49830, 52302, 52303, 47388, 49832, 49833, 52305, 49834, 47392, 49836, 47393, 49837, 49838, 52310, 52311, 49839, 47395, 49840, 52312, 47684, 52313, 52314, 48977, 49843, 48978, 52317, 52319, 49848, 52320, 50116, 52321, 52322, 52338, 52339, 52353, 52356, 52357, 52358, 52359, 49223, 45252, 49441, 45253, 47938, 49232, 47941
```
These had no meanings attached to them.

I've also disabled storing lexemes without a meaning in the database.
So the code that may try to do this should produce errors now.

**Comment by cormacanderson** [comment] 2016-11-20 19:01
This issue is, unfortunately, still not resolved. Below the email from our Wakhi expert:

"When I previously tried, I got the green overlay on the database page
that said lexeme 52356 created (for smooth), 52357 created (for
stick), 52358 created (for take) and 52359 created (for throw), but
the lexemes did not show on the database.

After your message that the programmer had worked on the bug fix, I
tried to post these:
smooth = šəluṭ̣
stick =  šəpk
take = yund

and got the "server could not add the requested lexeme" message on the
add lexeme page. Of course, no changes appeared on the main database
page. I stopped after trying the above 3 lexemes.

So something was changed, but not "fixed".

It was @ 9:00 PM PST.  I'm using a MacBook Pro running OS 10.6.8, with
a Firefox browser.  Given the "server could not add" message, it seems
more like a server side error, esp. as the programmer was working on
this issue."

**Comment by runjak** [comment] 2016-11-21 08:33
I found a hint for this problem in the server logs:
![screenshot_2016-11-21_09-31-25](https://cloud.githubusercontent.com/assets/5417642/20475753/87905190-afcd-11e6-8950-924861769ed7.png)

**Comment by runjak** [comment] 2016-11-21 08:58
Okay - one way I can reproduce this is to just not enter anything in the `Meaning` field of this form:
![screenshot_2016-11-21_09-46-14](https://cloud.githubusercontent.com/assets/5417642/20476116/8e6405a0-afcf-11e6-9902-4d13a6a6e10b.png)
I'll add a safeguard that prohibits sending the form without entering a meaning in it:
![screenshot_2016-11-21_09-55-27](https://cloud.githubusercontent.com/assets/5417642/20476343/c98aba92-afd0-11e6-947e-ec9af29108b2.png)
The fields for `meaning_id` and `language_id` that will be sent to the server will now be displayed. It will be possible to enter the IDs into these fields directly, but the already existing fields for `Meaning` and `Language` which have typeahead support will still fill them in.

**Comment by runjak** [comment] 2016-11-21 09:24
@cormacanderson I've deployed this recent adjustment to the form.
Could you check back with the data entry person if the problem still persists
and maybe ask if they payed attention to the `Meaning` and `Language` fields beforehand?
I've got the hunch that these haven't been prominent enough which combined with the possibility to send the incomplete form led to problems with data entry.

**Comment by PaulHeggarty** [comment] 2016-11-21 09:40
Presumably, some of these values should be pre-filled in automatically depending on which form view the add lexeme button was pressed  from.
* From 1-Language view, the values for Language and Language ID should be filled in with the values for that language.
* From 1-Meaning view, he values for Meaning and Meaning ID should be filled in with the values for that meaning.
Bear in mind also that people do not tend to know the meaning and language ID numbers, so asking them to enter this will be a big hassle.  It would be better just to ask them to enter the 'names', but only allow them to choose by typing, using the same system as for changing the language name header in `1-Language, All Meanings`, and for changing the meaning name header in `1-Meaning, All Languages`.  Ideally, that would be the system, without asking for ID numbers at all.

**Comment by runjak** [comment] 2016-11-21 10:35
@PaulHeggarty did you look at the forms? These fields are pre-filled where possible.

**Comment by PaulHeggarty** [comment] 2016-11-21 10:55
I looked at the screenshot above, where only one field seems pre-filled, Meaning ID, but not Meaning.  Or did you mean that the only way you could reproduce this was by actively deleteing the pre-filled entry for Meaning?  Maybe I misunderstood that.  Whatever, it's great if fields are pre-filled, that's already done!  Sorry for any confusion.

**Comment by runjak** [comment] 2016-11-21 10:58
It's all good.
I agree that it would be good not having to display the ID fields here.
The thing is just that it is possible to miss the `Meaning` inputs and I cannot set the ID fields to required when they're hidden (browsers complain).
So the ways to go here where:
* Either display the ID fields in addition to the non-id fields but still let the ID fields be filled in by their non ID counterparts
* Or spend longer time writing a piece of JS that complains to the user when they try to send the form without specifying a meaning.

I took the first route just because it was the simpler solution (stopping to hide the input) and would open up the possibility to use the ID if we wanted.
I can also go for the second option if you like but I assumed that it wouldn't be the best use of my time so far (because several things appeared to be broken).

**Comment by PaulHeggarty** [comment] 2016-11-21 11:04
OK, solution 1 seems ok.  So will both the 'name' and ID number fields be pre-filled in, though?

**Comment by runjak** [comment] 2016-11-21 11:06
Yes, both of them are pre-filled.

**Comment by runjak** [comment] 2016-11-23 20:00
Since no negative feedback was given the last two days I assume that this is solved.
Otherwise please notify me and/or reopen.

**Closed by runjak** 2016-11-23 20:00 UTC
Labels: 0th, Time 3: Few Hours, Website: Bug
