### ISSUE TITLE
Bug in PIE 1 lang - all mean list and in individual lexeme page(s)

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#101] opened 2016-03-08 12:15 UTC
http://134.76.24.144/language/Proto-Indo-European/wordlist/Jena200/

Three problems:

- I can't enter a root form for the first entry of the BITE words (*gʷerh₃-), and if I try to, the entered root appears also in the root form field of the line of the third BITE entry (*h₁ed-) and the second BLACK entry (*h₂ems-; did not check for others more).

- Originally, I tried to delete the lexem *gʷerh₃-, because it is not the Swadesh term and no cognacy classes have been assigned to it anyway. I used the individual lexeme page http://134.76.24.144/lexeme/23723/, but neither the 'Delete'-Button for the Lexeme nor the 'Delete'-Button for the source Frisk works.

- The 'Dubious'-Button did not work for the entry for BAD.

**Comment by runjak** [comment] 2016-03-11 13:39
I can confirm that an inputs for the `Root Form` field appear to be mirrored to other fields incorrectly. I'll see what I can do about this and how best to fix it.

**Comment by runjak** [comment] 2016-03-11 13:55
I figured out where the problem with the checkboxes stems from.
Because of older versions of the code using the wrong approach to encode/decode boolean fields such current cases broke when I switched it to a sane method.

**Comment by runjak** [comment] 2016-03-12 13:03
After deploying aa0b4bf0fe67343fc17eaf94eb6e5c8a65b884cb just now entering data should work again.
The incorrect mirroring of content across some rows still needs to be addressed as does the deletion of lexemes.

**Comment by runjak** [comment] 2016-03-14 12:30
I've figured out that the mirroring appeared when a lexeme was not a member of any cognate class. This is because the RootForm and RootLanguage attributes are stored in the lexemes cognate class. And thus this class is used to figure out which entries of RootForm and RootLanguage should contain the same content. To fix this I've disabled the input fields for RootForm and RootLanguage in the specific cases.

**Comment by CasFre** [comment] 2016-03-14 12:40
What do you mean by 'disabled'?
I closed the database website and logged in again, but I don't perceive any change as far as the mirroring-problem is concerned...

**Comment by runjak** [comment] 2016-03-14 13:27
Yeah - I haven't updated the site on the server.
I will only do that once I got all things in place.
But I can already provide a screenshot from my local development setup:
![screenshot_2016-03-14_14-25-45](https://cloud.githubusercontent.com/assets/5417642/13745864/b0640a4c-e9f0-11e5-9209-8382a07a3b9b.png)
As you can see, the entries that don't have a cognate class associated (nCog = 0) don't have the corresponding input fields for rootForm and rootLanguage.

**Comment by runjak** [comment] 2016-03-14 13:35
So the thing I haven't looked at so far are the deleted buttons.
I'll try to figure out what's broken with them now.

**Comment by runjak** [comment] 2016-03-14 15:22
OK, so I could gather some information on the button problem.
When first viewing the desired lexeme, it appears necessary to delete the remaining cognate classes first, before deleting it.
![predelete](https://cloud.githubusercontent.com/assets/5417642/13749204/9f73e88c-ea00-11e5-94ba-34aba09a0b5f.png)
It is not possible to remove the last source for a lexeme, but also not necessary.
After deleting the last Cognate Class, we can hover the deletion button…
![deletecc](https://cloud.githubusercontent.com/assets/5417642/13749237/bc29a0d4-ea00-11e5-9d2c-7de45599edc5.png)
It now shows the info that it is necessary to append `/delete/` to the end of the current URL to delete the lexeme. There was a bug preventing this message from being displayed, which I fixed.
The deletion of lexemes should in my opinion be doable via the button itself after displaying a confirmation dialog. I will deploy the fix to display the message soon.

**Comment by runjak** [comment] 2016-03-14 15:38
I've just rolled out the changes mentioned above.
The following issues should be solved:
* It should be more clear how to delete lexemes with the current setup
* It should again be possible to edit all editable entries in the edit tables,
including check-boxes.
* The problem where text from inputs was mirrored to other input boxes should be solved,
because said inputs turned out to be displayed by accident and are now removed.

I will open a new issue for the case of the delete button to make it possible to set a priority for the issue and see what others think of it. From there I will reference this issue to keep them connected.

I will further close this issue as I feel that the problems have been addressed.
Should something be missing please either reopen this issue or open a new one.

**Closed by runjak** 2016-03-14 15:38 UTC
Labels: 1st: Do Now!, Website: Bug
