### ISSUE TITLE
Erratic behaviour of loan, exl, Loan Event columns

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#88] opened 2016-02-23 10:34 UTC
These do not seem to be working properly.

**Comment by cormacanderson** [comment] 2016-02-23 10:35
Compare from the Old Irish list "cúl" and "olc"
![bad-olc](https://cloud.githubusercontent.com/assets/8975419/13248903/69bd8570-da21-11e5-9d92-bd34c896cfa3.png)

![back-cul](https://cloud.githubusercontent.com/assets/8975419/13248895/5bdbaf5e-da21-11e5-8265-79f197b01396.png)

**Comment by cormacanderson** [comment] 2016-02-23 10:35
Now compare their records:
![cul](https://cloud.githubusercontent.com/assets/8975419/13248949/9954d9dc-da21-11e5-97ef-288367b8a48c.png)
![olc](https://cloud.githubusercontent.com/assets/8975419/13248950/99559796-da21-11e5-9adf-a38e3cf11004.png)

**Comment by cormacanderson** [comment] 2016-02-23 10:39
Neither have been marked as Non-Swh in the checkbox. Why does olc correctly appear with a tick in the excl column (second checkbox after the cursor in the first pic), but cúl does not? Also, why is there no Loan Event box for cúl?

**Comment by PaulHeggarty** [comment] 2016-04-13 22:44
Cormac seems to have nailed this in his email just now.  Can’t be sure from the cropped image file, but it looks like cúl is assigned to 0 cognate sets.  And there is the problem.

**Comment by PaulHeggarty** [comment] 2016-04-13 23:28
Uprating this to level 1 again, but this is not a simple thing.  We need a full meeting on this when we can all get to it.  Cormac isn’t back until Monday.

**Comment by PaulHeggarty** [comment] 2016-04-14 19:43
Couldn't actually reproduce the above problem today, but I did find this:
![screenshot - 14_04_2016 21_37_53](https://cloud.githubusercontent.com/assets/8819910/14541235/3f1c5bc6-0289-11e6-8b2e-6ffde1623239.png)
Of these six Assamese entries, if you go into the individual records, you will see that numbers 1, 5 and 6 are all marked as exclude in the sources of LEXEME data, but they can’t be marked as exclude in the COGNATE coding, of course, because they're not assigned to any cognate set.  
And in the image, you can see that they are NOT marked as exclude in our excl column.  So it seems that our excl column is not working, it is only entering a check box if a COGNATE SET is marked as exclude, but it should do so also if the LEXEME is marked as exclude.  This is reminiscent of the problem in the export script, and perhaps the fix is the same.  Jakob?

**Comment by PaulHeggarty** [comment] 2016-04-14 19:44
The other three examples in Assamese are working fine … and they have been assigned to cognate sets.  ;)

**Comment by PaulHeggarty** [comment] 2016-04-14 19:45
When you send me the latest fixed export, Jakob, I’ll drill down into the nexus to see whether these are getting excluded properly in the export now, at least.

**Comment by runjak** [comment] 2016-04-18 11:44
Looking at [lexicon/models.py](https://github.com/lingdb/CoBL/blob/devel/ielex/lexicon/models.py#L735-L749) it becomes apparent that my current code for the checkboxes is buggy.
It only checks for loan/excl status in cognatejudgements instead of also considering lexemejudgements.
We should have separate checkboxes for these cases and display them both correctly.

**Closed** 2016-04-18 12:58 UTC
Labels: 0th:  !, 1st: Do Now!, Website: Bug
